### ISSUE TITLE
How to retrieve input value?

### ISSUE THREAD

**Issue by nugra** [gkueny/react-native-pin-code#11]
I need to retrieve input pin as parameter to process new page, how to get input pin?

thanks,

Nugra

**Comment by gkueny** [comment]
Hello @nugra ,

you can use `checkPinCode` prop : 

```js
<CodePin
     ...
     checkPinCode={(code, callback) => processNewPage(code, callback)}
/>
```

is it ok for your need ?

**Comment by Plukers** [comment]
Hey,
since the `success`  prop takes a function, would it be viable to pass the correct code to that function?
Or do you mean  that `checkPinCode` should be used instead of success in the case it's required?

Thanks for the great package btw!

**Comment by gkueny** [comment]
Hi @Plukers,

Currently, `success` function is call only when user fill the good pin code. So, you already have _the correct code_ because you pass it to PinCode component with `code` prop.

`checkPinCode` has to be used when : 
- you don't know the correct code and you have to verify the input pin with a third service (API, etc..)
- you just want to get the input pin and process it

I close because it's not a real issue, but i'm open to continue the discussion here

**Comment by Plukers** [comment]
Hey @gkueny,
thanks for the great explanation. I used `checkPinCode` as a pure function in a way that it does nothing besides checking the pincode.
And since I used it only to check the pincode but not to save it (I need it at another part of my app), I was missing the pincode in the `success` callback.

But I understand your explanation and also see that my usecase is not a general usecase, so I will just save the entered pincode during `checkPinCode`.

Thanks for your time and the great explanation!
