### ISSUE TITLE
Is not clear how to get the PIN

### ISSUE THREAD

**Issue by roberto-rodriguez** [gkueny/react-native-pin-code#4]
After reading this: https://www.npmjs.com/package/react-native-pin-code 
and now seeing the source code, is still not clear how can I get the pin, since all you do is call the this.props.success() when complete the PIN, but it not pass any argument.

Any suggestions.
BTW the lib looks really cool.

**Comment by gkueny** [comment]
Hi !

I don't understand your question

For the moment, you choose a code and pass it to CodePin component like this : 

```
<CodePin
    code="1234"
     number={4}
    success={this.onSuccess}
/>
```

If the user fills in correctly the code (1234 here), `this.props.success()` is called. Otherwise, an error is shown.
I plan to add a "onError" prop which will be called when the user fills in a bad code (1325 for instance). 

Thank you for the compliment, don't hesitate to contribute

**Comment by roberto-rodriguez** [comment]
Thanks for your reply, totally understand now. I think you can close this issue (question)
